TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.3
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.15
  
  acc_lim_th: 5.0
  acc_lim_x: 4.0
  acc_lim_y: 0.0
  
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false
  
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 3 # Default 3, 8-15 for high speed comupters
  vtheta_samples: 20
  controller_frequency: 10
  
  meter_scoring: false
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.2
  
  publish_cost_grid: true
  
  dwa: false
  
  holonomic_robot: false
