TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.4
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.2
  escape_vel: -0.3

  acc_lim_th: 5
  acc_lim_x: 3
  acc_lim_y: 0

  holonomic_robot: false

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.25

  sim_time: 1.5
  sim_granularity: 0.025

  meter_scoring: false 
  path_distance_bias: 0.1 
  goal_distance_bias: 0.8 
  occdist_scale: 0.05

  heading_scoring: true

  vx_samples: 8
  vtheta_samples: 5 

  dwa: false
